# Generated by Django 2.0.2 on 2018-02-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'ipv4'), (1, 'ipv6')], default=0)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, default=9735, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_channel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('flags', models.IntegerField(blank=True, default=0, null=True)),
                ('fee_per_millionth', models.IntegerField(blank=True, default=0, null=True)),
                ('base_fee_millisatoshi', models.IntegerField(blank=True, default=0, null=True)),
                ('delay', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(max_length=255, unique=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='source_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_source_destination', to='network.Node'),
        ),
        migrations.AddField(
            model_name='channel',
            name='source_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_source_node', to='network.Node'),
        ),
        migrations.AddField(
            model_name='address',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_node', to='network.Node'),
        ),
    ]
