# Generated by Django 2.0.2 on 2018-02-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='source_destination',
            new_name='destination_node',
        ),
    ]
